package dev.propulsionteam.computed.integration;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.neoforged.fml.ModList;
import org.jetbrains.annotations.Nullable;

/**
 * Reflection-based accessor for Create's kinetic block entities so the mod loads without Create.
 * All public methods return defaults ({@code 0}, {@code false}) when Create is absent or reflection fails.
 *
 * In Create's stress model, {@code calculateStressApplied()} and {@code calculateAddedStressCapacity()}
 * return base values multiplied by {@code abs(speed)} to get the actual SU values shown in the UI.
 */
public final class CreateKineticBridge {
    private static final String KINETIC_BE = "com.simibubi.create.content.kinetics.base.KineticBlockEntity";

    private static Boolean createPresent;
    private static Class<?> kineticClass;
    private static boolean classResolved = false;

    /** Cache resolved methods per (class, methodName) to avoid per-tick reflection overhead. */
    private static final Map<String, Method> methodCache = new HashMap<>();
    /** Sentinel stored in cache when a method is confirmed absent, to skip future lookups. */
    private static final Method ABSENT = buildAbsentSentinel();

    private CreateKineticBridge() {}

    public static boolean isCreateLoaded() {
        if (createPresent == null) createPresent = ModList.get().isLoaded("create");
        return createPresent;
    }

    @Nullable
    public static BlockEntity getKineticBlockEntity(Level level, BlockPos pos) {
        if (!isCreateLoaded()) return null;
        Class<?> cls = kineticClass();
        if (cls == null) return null;
        try {
            BlockEntity be = level.getBlockEntity(pos);
            if (be == null || !cls.isInstance(be)) return null;
            return be;
        } catch (Throwable t) {
            return null;
        }
    }

    public static boolean isKinetic(Level level, BlockPos pos) {
        return getKineticBlockEntity(level, pos) != null;
    }

    public static float getSpeed(Level level, BlockPos pos) {
        BlockEntity be = getKineticBlockEntity(level, pos);
        if (be == null) return 0f;
        return invokeFloat(be, "getSpeed");
    }

    /**
     * SU consumed by this block (0 for pure sources like motors).
     * Internally: {@code calculateStressApplied()} × abs(speed).
     */
    public static float getStress(Level level, BlockPos pos) {
        BlockEntity be = getKineticBlockEntity(level, pos);
        if (be == null) return 0f;
        float base  = invokeFloat(be, "calculateStressApplied");
        float speed = Math.abs(invokeFloat(be, "getSpeed"));
        return base * speed;
    }

    /**
     * SU capacity generated by this block (0 for pure consumers like presses).
     * Internally: {@code calculateAddedStressCapacity()} × abs(speed).
     */
    public static float getCapacity(Level level, BlockPos pos) {
        BlockEntity be = getKineticBlockEntity(level, pos);
        if (be == null) return 0f;
        float base  = invokeFloat(be, "calculateAddedStressCapacity");
        float speed = Math.abs(invokeFloat(be, "getSpeed"));
        return base * speed;
    }

    // --- Reflection helpers ---

    /**
     * Invoke a no-arg method and return the float result.
     * Returns {@code 0f} on ANY failure — method not found, access denied, exception thrown.
     * The entire call is wrapped so no exception can escape to the game thread.
     */
    private static float invokeFloat(Object obj, String methodName) {
        try {
            Method m = resolveMethod(obj.getClass(), methodName);
            if (m == null) return 0f;
            Object result = m.invoke(obj);
            return result instanceof Number n ? n.floatValue() : 0f;
        } catch (Throwable t) {
            return 0f;
        }
    }

    /**
     * Resolve a no-arg method, with results cached per (declaring class, method name).
     * Returns {@code null} if the method cannot be found or made accessible.
     * Never throws — all exceptions are swallowed and recorded as ABSENT in the cache.
     */
    @Nullable
    private static Method resolveMethod(Class<?> startClass, String methodName) {
        String key = startClass.getName() + "#" + methodName;
        Method cached = methodCache.get(key);
        if (cached == ABSENT) return null;
        if (cached != null) return cached;

        Method found = null;
        Class<?> cls = startClass;
        while (cls != null && cls != Object.class) {
            try {
                Method m = cls.getDeclaredMethod(methodName);
                try {
                    m.setAccessible(true);
                } catch (Throwable ignored) {
                    // setAccessible failed (module restrictions); try next class in hierarchy
                    cls = cls.getSuperclass();
                    continue;
                }
                found = m;
                break;
            } catch (NoSuchMethodException ignored) {
                // not declared in this class, walk up
            } catch (Throwable ignored) {
                // any other reflection error — give up on this class
            }
            cls = cls.getSuperclass();
        }

        methodCache.put(key, found != null ? found : ABSENT);
        return found;
    }

    @Nullable
    private static Class<?> kineticClass() {
        if (!classResolved) {
            classResolved = true;
            try { kineticClass = Class.forName(KINETIC_BE); } catch (Throwable ignored) {}
        }
        return kineticClass;
    }

    private static Method buildAbsentSentinel() {
        try {
            return CreateKineticBridge.class.getDeclaredMethod("isCreateLoaded");
        } catch (NoSuchMethodException e) {
            throw new AssertionError(e);
        }
    }
}
